mod commands;
mod pty;
#[cfg(windows)]
mod terminal_probe;
mod watcher;

pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_shell::init())
        .manage(watcher::WatcherState::default())
        .manage(pty::PtyRegistry::default())
        .invoke_handler(tauri::generate_handler![
            commands::ping,
            commands::home_dir,
            commands::list_dir,
            commands::drives,
            commands::list_wsl_distros,
            commands::system_info,
            commands::make_dir,
            commands::rename_entry,
            commands::copy_entry,
            commands::move_entry,
            commands::delete_entry,
            commands::move_to_trash,
            commands::read_text,
            commands::write_text,
            commands::read_image_b64,
            commands::git_status,
            commands::git_blame,
            commands::git_stage,
            commands::git_unstage,
            commands::git_discard,
            commands::git_run,
            commands::git_branch_list,
            commands::git_ahead_behind,
            commands::find_in_files,
            commands::cancel_find_in_files,
            commands::compress,
            commands::archive_create,
            commands::archive_extract,
            commands::archive_can_handle,
            commands::hash_sha256,
            commands::open_with_default,
            commands::reveal_in_explorer,
            commands::spawn_terminal,
            commands::spawn_vscode,
            commands::win_to_wsl,
            commands::wsl_to_win,
            commands::read_pins,
            commands::write_pins,
            commands::read_tags,
            commands::write_tags,
            commands::set_permissions,
            commands::read_hex_dump,
            commands::diff_files,
            commands::find_file_by_name,
            commands::create_symlink,
            commands::create_hard_link,
            commands::create_shortcut,
            commands::shred,
            commands::verify_signature,
            commands::change_owner,
            commands::run_script,
            commands::open_url,
            commands::spawn_new_window,
            commands::set_always_on_top,
            commands::list_shell_profiles,
            commands::spawn_terminal_profile,
            commands::read_recent,
            commands::append_recent,
            commands::clear_recent,
            commands::file_stat_extended,
            commands::hash_md5,
            commands::hash_crc32,
            commands::git_file_info,
            commands::path_fs_type,
            commands::net_rate,
            commands::git_dirty_count,
            watcher::watch_dir,
            watcher::unwatch_dir,
            pty::pty_spawn,
            pty::pty_write,
            pty::pty_resize,
            pty::pty_kill,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
